### ISSUE TITLE
warmup20160306to20160313 一些总结

### ISSUE THREAD

**Issue by Akiq2016** [Akiq2016/UU_warmup20160306#27]
>>先对我的队友表示感谢：@Pc6 @wisdomfree @LDQ-first @bottle1125  排名按入队顺序。
素未谋面的我们，来自不同的学校，带着同样想要进步的想法。
通过分工合作，我们写了团队第一个页面：
http://akiq2016.github.io/UU_warmup20160306/AboutUuTeam.html

**页面设计的来由**
- 最初， @Pc6 提出模仿知乎页面，做团队介绍。而后我提供了优设的一篇团队展示页面的文章，里面的设计方案很值得借鉴，在这里也放一下链接，方便看到的各位学习：http://www.uisdc.com/50-wonderful-aboutus-webpage  。
- 然后， @wisdomfree 表示他想尝试整个屏向上滚动的页面效果，于是我就提供了fullpage.js的链接：https://github.com/alvarotrigo/fullPage.js  。
- 至此，我们已经决定了这个方向， @wisdomfree  提供了可借鉴的页面：https://www.tumblr.com  。我之所以说通过汤不热的页面找到灵感，是因为潜意识中理解的fullpage更多是利用在摄影啊旅游业啊或产品展示等，即需要高清大图。看了汤不热就猛一拍脑：啊sb，可以用色块嘛hhhh。

**团队的整体水平**
- 分工合作后，在一个星期里遇到不少问题。大家都是新使用github，在前半段时间里，一直都有pull request失败等问题。但庆幸在明天的任务开始前，我们已经会基本的操作，从0起点变成0.2起点。
- 5个人都表示 熟悉或者正在了解 html css JavaScript 以及 jQuery。事实上我们在这次页面中也是用这些。但是5个人的实际水平有一定差距。学习的视频或许都看了不少，但是实际的让自己去写，真的远远不够。
- 共勉： 多练多记。

**page1我遇到过的问题**

- 问题1：page1有一个大的png背景图片，页面缩小的话，就看不到图片了，在朋友的建议下，我把原本 @bottle1125 的html修改了一下：
```html
<h1 class="sym" id="sym0">
     <span id="universe">UNIVERSE </span>#$%&amp;
     <span id="university">UNIVERSITY</span>
</h1>
<p>相识 相知 队友你好</p>
```
change to
```html
<div class="s1-tit">
	<h1 class="sym" id="sym0">
		<i id="s1-tit-1">Universe University</i><i id="s1-tit-2">of Technology</i>
	</h1>
</div>
<div class="s1-bg"></div>
<div id="s1-pmove" class="s1-p">
	<p>相识 相知 队友你好</p>
</div>
```
```css
/* 3 div ：title  background  p */
.s1-tit{height: 40%;text-align: center;}
.s1-bg{height: 50%;min-height: 305px;background: url(../images/1.png) center;background-size: cover;}
.s1-p{height: 10%;}
```
- 问题2：页面加载完成后，第一次从page1滑动到page2时，渐变效果有bug。这是因为没有初始化完全。具体说明和解决方案看 #8 (对于初次加载页面后 page1->page2的背景渐变有bug的原因解释)。
- 问题3：遗留bug。在其他页面做 [网页初次加载] 的情况下，滚动回第一屏，p标签没有opacity的渐变效果。望路过好心人踹醒我木鱼脑袋，为我指点一二。

**page2我遇到过的问题**

- 想利用伪元素给introduction box添加翘边阴影。但是发现：box上原有的transform:scale(1.1)这个hover状态的样式，导致了给伪元素设置的z-index失效，即.intro_box:after .intro_box:before的存在样式，无法藏在intro box之下，反而始终显示在最上。最后我选择了删除hover状态下的transform样式，改成了用jq控制样式，但是效果并没有css3的好：
```js
$('.intro_box').mouseenter(function(){$(this).css({'width':'231px','height':'275px'});})
                      .mouseleave(function(){$(this).css({'width':'210px','height':'250px'});});
```
但是为什么z-index会因此失效，并没有找到答案，如果有人知道，也请为我指点一下。顺便附上我最初了解伪元素的文章：http://blog.jobbole.com/49173/  ， 以及学习具体代码的慕课视频链接：http://www.imooc.com/learn/240

**左上角fixed导航我遇到过的问题**

- 这个导航是昨天 @LDQ-first 提出加的。在样式上面，我希望当前选中项即为当前页面背景色块，同时，在页面滚动过程中，能随背景颜色一样，是过渡变换的。以下是 @LDQ-first 代码：
```html
	<header class="hd">
		<div class="inner">
	        <nav>
	        	<ul id="menu">         
	            	<li class="active" data-menuanchor="Page1"><a href="#Page1">开启新旅程</a></li>
	                <li data-menuanchor="Page2"><a href="#Page2">团队介绍</a></li>
	                <li data-menuanchor="Page3"><a href="#Page3">分工&制作说明</a></li>
	            </ul>
	        </nav>
	    </div>
	</header>

```
```css
 .hd {
     width: 100%;
     height: 45px;
     background: rgba(255, 255, 255, 0.2);
     position: fixed;
     top: 0;
     left: 0;
     z-index: 1;
 }......
.hd nav li:nth-child(1).active a {
     background: #FF5CA0;
     color: rgba(0, 0, 0, 0.6)
 }
.hd nav li:nth-child(1) a:hover{
    background:transparent;
    color: rgba(0, 0, 0, 0.6)
}
.hd nav li:nth-child(2).active a {
     background: #37DF5F;
     color: rgba(0, 0, 0, 0.6)
 }
.hd nav li:nth-child(2) a:hover{
    background:transparent;
    color: rgba(0, 0, 0, 0.6)
} ....
```
问题在于直接对3个a标签设置了颜色，所以在页面滚动时，并没有随背景一起颜色过度。而后将颜色修改为了transparent也不行。
通过层级结构，可以知道a标签是覆盖在最上面的，而当a标签transparent后，显示的颜色是在a下面的最近一个 有颜色的.hd ：background: rgba(255, 255, 255, 0.2); 由此可见，a下面是个有透明度的白色，而不是当前页的背景颜色。
因此解决办法是删掉.hd的背景颜色，把rgba(255, 255, 255, 0.2)直接给每一个a标签，而当前a标签 则设置为透明，即能直接显示为当前页面的背景颜色。问题解决，并因此简化了代码：
```css
.hd {
    width: 100%;
    height: 45px;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1;
}
.hd nav li a {
    line-height: 45px;
    padding: 0 20px;
    background: rgba(255, 255, 255, 0.2);
    color: #fff;
    font-size: 14px;
    display: block;
    transition: all 0.5s;
}.......
.hd nav li.active a,
.hd nav li.active a:hover,
.hd nav li a:hover {
    background: transparent;
    color: rgba(0, 0, 0, 0.6);
}
```
-----------------------------------------------------
**个人看到的页面中的不足之处**
- 没有做成响应式。在移动设备上看页面比较糟糕。能力有限，不能在一个星期里完成。不过后续我个人打算在原代码基础上把他补充好。
- 网速不好的话，第一次打开网页，页面是不完整的，只有一张png图片，体验不好，应该在加载完成前，添加页面加载等待界面。
- 如果页面来回滚动比较快，所涉及到的页面上的动画，可能会没有重置完，或者还在运动中，不知道这个有没有解决办法。
